Make bit_cast static and fix noexcept warning
C++17 adds the exception specification to function types, which are part
of mangled symbol names, so make the name mangling problem go away by
making this function (which should always be inlined anyway) `static`.
Another alternative would be to add `noexcept`.

```
runtime/globals.h:107:10: error: mangled name for ‘D bit_cast(const S&) [with D = void*; S = void* (*)(void*, int, long unsigned int) throw ()]’ will change in C++17 because the exception specification is part of a function type [-Werror=noexcept-type]
 inline D bit_cast(const S& src) {
```